# Generated by Django 4.0 on 2022-08-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img_news'),
        ),
    ]
